### ISSUE TITLE
I don't think the FOX Tookit support GNU Hurd!

### ISSUE THREAD

**Issue by Curculigo** [franko/fox#14]
Please review the list of supported host systems:

```
supported_host_systems = ['windows', 'cygwin', 'linux', 'netbsd', 'freebsd', 'gnu']
```

`gnu` is GNU Hurd according to this table:

https://mesonbuild.com/Reference-tables.html#operating-system-names

**Comment by Curculigo** [comment]
Btw, please add `openbsd`, `dragonfly`, `sunos`, and maybe `emscripten`, too.

**Comment by franko** [comment]
Hi, thank you, I fixed this problem in the master branch.
